### ISSUE TITLE
Make a guide for M-of-N Multisignature wallets

### ISSUE THREAD

**Issue by KeeJef** [loki-project/loki-docs#39]
We need a guide to be written for M-of-N for example 3 of 5 keys required to send Loki, 
this can also probably been up streamed to Monero docs since they are also missing a guide like this

**Comment by Sonofotis** [comment]
I'll wait till we implement mms functionality into the loki-wallet-cli before writing this document. Transfer.sh isnt a secure means of sending key files.

**Comment by Sonofotis** [comment]
M-of-N

`make_multisig <threshold> <MS_data_1> [<MS_data_2> ... <MS_data_N>]`

Where `<threshold>` = M and `<MS_data_N>` = the N'th person of the multisig wallet.

**Comment by Sonofotis** [comment]
Guide finished as of https://github.com/loki-project/loki-docs/commit/5636befe539bd4860da6e46386ad93e4733ac53e
