### ISSUE TITLE
disable google analytics

### ISSUE THREAD

**Issue by majestrate** [loki-project/loki-docs#49]
from https://loki-project.github.io/loki-docs/

>Privacy is having the agency to decide when you reveal personal information. It is a particularly valuable quality today, when the collection and storage of personal data is taking place at unprecedented levels in history.

yet there are google analytics on the page. 

this should be disabled ASAP as we're a privacy project after all.

**Comment by majestrate** [comment]
#50 fixes this

**Comment by gea0** [comment]
The site still loads fonts from fonts.googleapis.com

I suggest to remove that too - the site works fine without them.

**Comment by Sonofotis** [comment]
Fonts from google apis removed.
https://github.com/loki-project/loki-docs/commit/170e7a80be2d3cba0c436e1dc727c8ff776db051
