### ISSUE TITLE
Submitting translations

### ISSUE THREAD

**Issue by ChanoSan** [loki-project/loki-docs#66]
I've spoken to a member of this project about translating Loki-Docs into Japanese. I've been told to submit them to the repo, so I've forked it and plan to add the translated files into a folder "JP" parallel to "docs" in the top directory. Is this acceptable, or is there a better way to organize it?

I'm not very familiar with Github (or git), and I've never forked or sent a pull request before, so I'm hoping I don't screw up too much, but apologies in advance.

Thanks.

**Comment by Sonofotis** [comment]
That's great news Chano! 

I see your fork is here: https://github.com/ChanoSan/loki-docs

Jump into terminal and run the following command to pull all the files onto your local machine
```git clone https://github.com/ChanoSan/loki-docs```

Then you can make the edits. Give me a buzz in here if you need anymore help.

**Comment by ChanoSan** [comment]
Thanks.

I did have a question about branches...should I make the JP translations a branch under master, or would something else be better? I'll try my first pull request once I've added the first completed section.

**Comment by Sonofotis** [comment]
If you keep working on it on your own branch we can move it over to the Loki repository when it's ready.

**Comment by ChanoSan** [comment]
Understood... still a lot of work to go, but once it's done I'll be in touch.
