### ISSUE TITLE
Persistent SNapp guide states directories incongruent with pre-built binary installation locations

### ISSUE THREAD

**Issue by necro-nemesis** [loki-project/loki-docs#68]
Pretty much what the title says. It's not installed under the home dir.

**Comment by jagerman** [comment]
With the debs things get installed into system directories: /etc/loki/lokinet.ini for the snapp package.  There are some rough edges there, though, as to how ancillary configuration gets stored/updated that are on the roadmap for the next release.

**Comment by Sonofotis** [comment]
https://github.com/loki-project/loki-docs/commit/39e0dc17d510db527f234942b7efdca34be0062b

Fixed as per the above commit.
