### ISSUE TITLE
lsb_release causing issues for multiple debian distros

### ISSUE THREAD

**Issue by tinhat99** [loki-project/loki-docs#70]
I am running a Debian distro called MX Linux.  This distro also has problems with lsb_release.  It appears Linux Mint also has issues as reported by another user.  

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: MX
Description:    MX 18.3 Continuum
Release:        18.3
Codename:       Continuum
```
Would it not be best to pull the distro from the /etc/os-release file?
```
$ cat /etc/os-release | grep VERSION_CODENAME | awk -F "=" "{ print $2}"
stretch
```
End result would be:
```
echo "deb https://deb.imaginary.stream $(cat /etc/os-release | grep VERSION_CODENAME | awk -F '=' '{print $2}' ) main" | sudo tee /etc/apt/sources.list.d/imaginary.stream.list
```
I will be glad to put in a pull request if there is agreement on this approach.

**Comment by Sonofotis** [comment]
That sounds like a better approach if it covers all operating systems. 

Send the PR through when you can.
